add_link_loss: false
aug_type: feature
batch_size: 64
clutering_iters: 3
cross_prune: 0.8
empty_pretrained_dir: false
entropy_div_ratio: 3
eval_step: 10
gamma: 0.5
gnn_batch_size: 64
gnn_dropout: 0.4
gnn_eval_step: 10
gnn_gamma: 0.5
gnn_h_dim: 512
gnn_lr: 0.01
gnn_n_epochs: 100
gnn_num_layers: 3
gnn_step_size: 50
gnn_type: gcn
h_dim: 512
hard_labels: false
inner_prune: 0.3
iterative_clustering: false
dropout: 0.3
lr: 0.001
n_epochs: 30
n_raug: 0.15
neg_aug_mode: arbitrary
noise_cov_scale: 1.0
noise_mean_shift: 1.0
noise_shift_mode: homophily
num_runs: 2
p_raug: 0.05
p_shift_inter: null
p_shift_intra: null
pos_aug_mode: mask
prompt_fn: gpf_plus
prompt_method: flex_match
r_reg: 0.0
s_dataset: DHFR
save_pretrained: true
seed: 1234
shift_type: structural
step_size: 50
src_ratio: 0.5
t_dataset: DHFR
total_iters: 2
w_domain_loss: 0.5
w_entropy_loss: 0.0
w_softmax_loss: 0.0
weight_decay: 0.2
label_reduction: 0.0
cut_off: 0.5
light_aug_prob: 0.2
light_aug_mode: mask
num_tokens: 50
t_split:
- 0.65
- 0.30